image: openjdk:11

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "/usr/local/gradle"

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
    - unzip -d /usr/local/gradle gradle-6.8.3-bin.zip
    - export GRADLE_HOME=/usr/local/gradle/gradle-6.8.3
    - export PATH=$PATH:$GRADLE_HOME/bin
  script:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - chmod +x ./gradlew
    - ./gradlew testDebug
