image: openjdk:11-jdk

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/gradle"
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_HOME: "/opt/android-sdk"

before_script:
  - apt-get update && apt-get install -y curl unzip

build:
  stage: build
  script:
    - cd Client
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - java -version
    - chmod +x ./gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - java -version
    - chmod +x ../gradlew
    - ../gradlew testDebug
