image: adoptopenjdk:11-jdk-hotspot

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y wget unzip

variables:
  GRADLE_HOME: "$PWD/gradle-7.2"
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

build:
  stage: build
  script:
    - cd Client
    - wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
    - unzip -qq gradle-7.2-bin.zip
    - export PATH=$GRADLE_HOME/bin:$PATH
    - chmod +x gradlew
    - wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
    - tar xf openjdk-11+28_linux-x64_bin.tar.gz
    - export JAVA_HOME=$PWD/jdk-11
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - export PATH=$JAVA_HOME/bin:$PATH
    - ./gradlew test
