image: openjdk:11-jdk

stages:
  - build

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends wget tar unzip
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-sdk.zip
  - unzip -q android-sdk.zip -d android-sdk
  - echo "y" | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "platform-tools" "platforms;android-30" > /dev/null
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64


build:
  stage: build
  script:
    - cd Client
    - export ANDROID_HOME=/android-sdk
    - export PATH=$PATH:$ANDROID_HOME/emulator
    - export PATH=$PATH:$ANDROID_HOME/tools
    - export PATH=$PATH:$ANDROID_HOME/tools/bin
    - export PATH=$PATH:$ANDROID_HOME/platform-tools
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:

      - Client/app/build/outputs/
