image: openjdk:11

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/gradle"

before_script:
  - apt-get update && apt-get install -y wget unzip

build:
  stage: build
  script:
    - cd Client
    - export JAVA_HOME=/usr/local/openjdk-11
    - export PATH=$PATH:$JAVA_HOME/bin
    - java -version
    - chmod +x ./gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - export JAVA_HOME=/usr/local/openjdk-11
    - export PATH=$PATH:$JAVA_HOME/bin
    - java -version
    - chmod +x ../gradlew
    - ../gradlew testDebug
