image: openjdk:11

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/gradle"

before_script:
  - apt-get update && apt-get install -y curl unzip

build:
  stage: build
  script:
    - cd Client
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk install java 11.0.12.hs-adpt
    - java -version
    - chmod +x ./gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk install java 11.0.12.hs-adpt
    - java -version
    - chmod +x ../gradlew
    - ../gradlew testDebug
