image: openjdk:11

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y wget unzip

build:
  stage: build
  script:
    - cd Client
    - wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
    - unzip -qq gradle-7.2-bin.zip
    - export PATH=$PWD/gradle-7.2/bin:$PATH
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 
    - chmod +x gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - ./gradlew test
