image: openjdk:11

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/gradle"
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_ROOT: "/opt/android-sdk"

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java
  - java -version
  - yes | sdkmanager "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS"

build:
  stage: build
  script:
    - cd Client
    - export ANDROID_HOME=$ANDROID_SDK_ROOT
    - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
    - chmod +x ./gradlew
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - cd Client
    - export ANDROID_HOME=$ANDROID_SDK_ROOT
    - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
    - chmod +x ../gradlew
    - ../gradlew testDebug
